Hotfix/17.0.1
5rabbits/speller pull request #1
Opened 2017-04-11 18:11 UTC by darkunter

## Problema ##
No funciona usar el corrector ortográfico para portugues.

## Análisis ##
Se levanta el proyecto localmente y luego se revisa el *output* de servidor al hacer un request. El resultado es el siguiente:
```
ArgumentError - The used dictionary "pt-br" is not available:
```

Al revisar el código, se encuentra que cuando el lenguaje enviado es portugues (pt), el script realiza lo siguiente:
```
lang = 'pt-br' if lang == 'pt'
```
Luego se revisa la lista de lenguajes disponibles en spell, usando el comando `spell dump dicts`, y se encuentra que el lenguaje correcto es **pt_BR**.

## Solución ##
Se cambia la llave `pt-br` por `pt_BR` cuando el lenguaje es `pt`

## QA ##

2017-04-11 18:17 UTC, mlavandero approved these changes

2017-04-12 20:36 UTC, a-bx requested changes
Por qué no agregar el archivo ahora?  de igual forma la lógia de fallback que se base en el mismo archivo de configuración.

2017-04-12 20:36 UTC, a-bx commented on speller.rb
> +    lang = 'pt_BR' if lang == 'pt'
OK. nada más que para el próximo idioma ya crearía un mapping en un archivo YML puesto que esto se llenará de If :)

2017-04-12 20:40 UTC, a-bx approved these changes

2017-04-12 23:19 UTC, GusGA commented on speller.rb
> +    lang = 'pt_BR' if lang == 'pt'
¿¿¿Un trabajo para YAMLMan???

2017-04-13 14:53 UTC, merged